# Generated by Django 5.1.3 on 2024-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_jobposting_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='link',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
